const state={reports:[],active:0};const $=id=>document.getElementById(id);
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){field+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field='';}else field+=c;}if(quoted)throw new Error('CSV has an unmatched quotation mark.');if(field||row.length){row.push(field);rows.push(row);}const headers=rows.shift()?.map(h=>h.trim().replace(/^\uFEFF/,''));if(!headers||!rows.length)throw new Error('CSV needs a header and at least one report.');return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,(values[i]||'').trim()])));}
function splitFindings(text){return(text.match(/FINDINGS:\s*([\s\S]*?)(?=\s*IMPRESSION:|$)/i)||[,text])[1];}
function sentences(text){return text.replace(/\s+/g,' ').match(/[^.!?]+[.!?]+/g)||[];}
function score(sentence){const text=sentence.toLowerCase();let points=0;if(/acute|hemorrhage|occlusion|leak|abscess|embol|pneumothorax|cord compression|active extravasation|infarct/.test(text))points+=12;if(/new|enlarg|increase|progress|obstruct|metasta|recurr|severe|mass effect/.test(text))points+=7;if(/no acute|unchanged|stable|unremarkable|normal/.test(text))points-=4;return points;}
function createDraft(report){const source=sentences(splitFindings(report.source_report_text)).filter(sentence=>sentence.trim().length>25);const ranked=source.map((sentence,index)=>({sentence:sentence.trim(),index,score:score(sentence)})).sort((a,b)=>b.score-a.score||a.index-b.index);const chosen=ranked.slice(0,3).sort((a,b)=>a.index-b.index);return chosen.map((item,index)=>`${index+1}. ${item.sentence}`).join('\n');}
function active(){return state.reports[state.active];}function renderList(){$('report-list').innerHTML=state.reports.map((report,index)=>`<button class="report-button ${index===state.active?'active':''}" data-index="${index}"><strong>${report.report_id}</strong><span>${(report.source_report_text.match(/EXAM:\s*([^\n]+)/i)||[])[1]||'Source report'}</span></button>`).join('');document.querySelectorAll('.report-button').forEach(button=>button.addEventListener('click',()=>{saveDraft();state.active=Number(button.dataset.index);render();}));}
function render(){const report=active();$('empty').hidden=Boolean(report);$('review-content').hidden=!report;$('count').textContent=`${state.reports.length} reports`;if(!report)return;renderList();$('report-id').textContent=report.report_id;$('source-text').textContent=report.source_report_text;$('draft-text').value=report.generated_impression||'';$('draft-status').textContent=report.generated_impression?'Draft ready':'Not generated';const hasReference=Boolean(report.suggested_impression);$('toggle-reference').hidden=!hasReference;$('reference').hidden=true;$('reference').textContent=report.suggested_impression||'';}
function saveDraft(){if(active())active().generated_impression=$('draft-text').value.trim();}
function generateCurrent(){const report=active();if(!report)return;report.generated_impression=createDraft(report);render();}
function quoteCsv(value){const text=String(value??'');return/[",\n\r]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;}
function exportRows(){saveDraft();const fields=[...new Set(state.reports.flatMap(row=>Object.keys(row).filter(key=>key!=='generated_impression'))),'generated_impression'];const csv=[fields.join(','),...state.reports.map(row=>fields.map(field=>quoteCsv(row[field])).join(','))].join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='generated-impressions.csv';link.click();URL.revokeObjectURL(link.href);}
function loadReports(rows,name){if(!rows.every(row=>'report_id'in row&&'source_report_text'in row))throw new Error('CSV needs report_id and source_report_text columns.');state.reports=rows.map(row=>({...row,generated_impression:''}));state.active=0;$('dataset').textContent=name;render();}
$('reports-upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{loadReports(parseCsv(await file.text()),file.name);}catch(error){alert(error.message);}e.target.value='';});$('generate-one').addEventListener('click',generateCurrent);$('generate-all').addEventListener('click',()=>{state.reports.forEach(report=>report.generated_impression=createDraft(report));render();});$('draft-text').addEventListener('input',saveDraft);$('export').addEventListener('click',exportRows);$('toggle-reference').addEventListener('click',()=>{$('reference').hidden=!$('reference').hidden;$('toggle-reference').textContent=$('reference').hidden?'Show suggested impression':'Hide suggested impression';});async function loadBundled(){try{const response=await fetch('../data/reports.csv');if(!response.ok)throw new Error();loadReports(parseCsv(await response.text()),'Bundled reports');}catch{$('dataset').textContent='Upload reports to begin.';render();}}loadBundled();
