const state={reports:[],active:0};const $=id=>document.getElementById(id);const fields=['modality','incidental','age','size','suspicious','comorbidity'];
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){field+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field='';}else field+=c;}if(quoted)throw new Error('CSV has an unmatched quotation mark.');if(field||row.length){row.push(field);rows.push(row);}const headers=rows.shift()?.map(h=>h.trim().replace(/^\uFEFF/,''));if(!headers||!rows.length)throw new Error('CSV needs a header and at least one report.');return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,(values[i]||'').trim()])));}
function candidates(report){const text=report.report_text;const lower=text.toLowerCase();const modality=/\bMRI\b/i.test(text)?'MRI':/\bCT\b/i.test(text)?'CT':'Uncertain';const incidental=/\bincidental\b/i.test(text)?'Yes':/\b(known|palpable)\b/i.test(text)?'No':'Uncertain';const age=(text.match(/\b(\d{1,3})\s*year-old\b/i)||[])[1]||'';const sizes=[...text.matchAll(/(\d+(?:\.\d+)?)\s*cm[^.\n]{0,90}\bthyroid\b/ig)].map(match=>Number(match[1]));const size=sizes.length?String(Math.max(...sizes)):'';const suspicious=/\bno suspicious[^.\n]*(lymph|node)|\bno (local|extrathyroidal).*invasion/i.test(text)?'No':/\b(suspicious[^.\n]*(lymph|node)|local invasion|extrathyroidal)\b/i.test(text)?'Yes':'Uncertain';return{modality,incidental,age,size,suspicious,comorbidity:report.limited_life_expectancy_or_major_competing_comorbidity||'Uncertain'};}
function evaluate(values){if(!['CT','MRI'].includes(values.modality))return{state:'Needs review',text:'Needs review',why:'Confirm that this is a CT or MRI finding before using this workshop pathway.'};if(values.incidental==='No')return{state:'Pathway not applicable',text:'Non-incidental thyroid nodule identified; thyroid best practice does not apply',why:'The workshop pathway only applies to incidental nodules.'};if(values.incidental!=='Yes'||values.suspicious==='Uncertain'||values.comorbidity==='Uncertain')return{state:'Needs review',text:'Needs review',why:'At least one required decision input remains uncertain.'};if(values.suspicious==='Yes')return{state:'Recommendation ready',text:'Recommend ultrasound follow-up',why:'Suspicious local invasion or regional lymph-node features use the follow-up route.'};if(values.comorbidity==='Yes')return{state:'Recommendation ready',text:'No follow-up imaging recommended',why:'The supplied context indicates limited life expectancy or a major competing comorbidity.'};const age=Number(values.age),size=Number(values.size);if(!age||!size)return{state:'Needs review',text:'Needs review',why:'Patient age and largest nodule dimension are needed for this branch.'};const threshold=age<35?1:1.5;return size>=threshold?{state:'Recommendation ready',text:'Recommend ultrasound follow-up',why:`Largest nodule is ${size} cm; the threshold for this age group is ${threshold} cm.`}:{state:'Recommendation ready',text:'No follow-up imaging recommended',why:`Largest nodule is below the ${threshold} cm threshold for this age group.`};}
function active(){return state.reports[state.active];}function values(){return Object.fromEntries(fields.map(field=>[field,$(field).value]));}
function renderList(){$('report-list').innerHTML=state.reports.map((report,index)=>`<button class="report-button ${index===state.active?'active':''}" data-index="${index}"><strong>REPORT ${String(index+1).padStart(2,'0')}</strong><span>${(report.report_text.match(/EXAM:\s*([^\n]+)/i)||[])[1]||'Source report'}</span></button>`).join('');document.querySelectorAll('.report-button').forEach(button=>button.addEventListener('click',()=>{state.active=Number(button.dataset.index);render();}));}
function render(){if(!active())return;renderList();const report=active(),candidate=candidates(report);$('report-label').textContent=`Report ${state.active+1}`;fields.forEach(field=>$(field).value=candidate[field]);$('report-text').textContent=report.report_text;$('evidence').textContent=`Candidate facts: ${candidate.modality}; incidental: ${candidate.incidental}; age: ${candidate.age||'unknown'}; size: ${candidate.size||'unknown'} cm; suspicious: ${candidate.suspicious}.`;updateResult();}
function updateResult(){const decision=evaluate(values());$('recommendation').value=decision.text;$('reasoning').textContent=decision.why;const chip=$('state-chip');chip.textContent=decision.state;chip.className=decision.state==='Needs review'?'review':decision.state==='Pathway not applicable'?'na':'';}
function loadReports(rows){if(!rows.every(row=>'report_text'in row))throw new Error('CSV needs a report_text column.');state.reports=rows;state.active=0;render();}
fields.forEach(field=>$(field).addEventListener('change',updateResult));$('reports-upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{loadReports(parseCsv(await file.text()));}catch(error){alert(error.message);}e.target.value='';});async function loadBundled(){try{const response=await fetch('../data/reports.csv');if(!response.ok)throw new Error();loadReports(parseCsv(await response.text()));}catch{$('report-label').textContent='Upload a report to begin.';}}loadBundled();
