const state={catalog:[],orders:[]};
const $=(id)=>document.getElementById(id);
const RULES={
  "MRI Brain WO Contrast":["headache","dizziness","nonfocal"],"MRI Brain WWO Contrast":["metast","intracranial tumor","enhancing lesion","neoplasm"],"MRI Brain FAST":["acute","sudden","aphasia","hemiparesis","facial droop","last known well","focal deficit"],"MRI Pituitary":["pituitary","prolactin","cushing","sellar"],"MRI Internal Auditory Canal":["hearing loss","tinnitus","vertigo","iac"],"MRI Brain Epilepsy":["seizure","deja vu","epilep"],"MRI Brain MS":["multiple sclerosis","demyelin","optic neuritis"],"MRI Brain Dementia":["memory","cognitive","dementia","executive"],"MRI Trigeminal Neuralgia":["trigeminal","facial pain","lancinating","electric shock"],"MRI Brain CSF Flow":["hydrocephalus","csf","ventriculomegaly","urinary urgency"],"MRI Brain With Perfusion":["glioblastoma","high-grade glioma","perfusion","post-treatment effect","chemoradiation"],"Radiologist Review":["uncertain implant","postoperative","several surgeries","skull-base","complex"]
};
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){field+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field='';}else field+=c;}if(quoted)throw new Error('CSV has an unmatched quotation mark.');if(field||row.length){row.push(field);rows.push(row);}const headers=rows.shift()?.map(h=>h.trim().replace(/^\uFEFF/,''));if(!headers||!rows.length)throw new Error('CSV needs a header and at least one row.');return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,(values[i]||'').trim()])));}
function routeOrder(order){const text=order.reason_for_exam.toLowerCase();const scores=state.catalog.map(item=>{const hits=(RULES[item.protocol_name]||[]).filter(word=>text.includes(word));return{item,hits,score:hits.length};}).sort((a,b)=>b.score-a.score);const best=scores[0],next=scores[1];if(!best||!best.score||(next&&best.score===next.score))return{route:'Radiologist Review',hits:[],review:true};return{route:best.item.protocol_name,hits:best.hits,review:best.item.protocol_name==='Radiologist Review'};}
function renderCatalog(){$('catalog').innerHTML=state.catalog.map(item=>`<div class="catalog-item"><strong>${escapeHtml(item.protocol_name)}</strong><span>${escapeHtml(item.clinical_description)}</span></div>`).join('');}
function render(){renderCatalog();const container=$('orders');container.innerHTML='';$('empty').hidden=Boolean(state.orders.length);$('summary').textContent=`${state.catalog.length} local routes loaded · ${state.orders.length} order${state.orders.length===1?'':'s'} ready`;state.orders.forEach((order,index)=>{const decision=routeOrder(order);order.predicted_protocol??=decision.route;const node=$('order-template').content.cloneNode(true);node.querySelector('.order-number').textContent=`ORDER ${String(index+1).padStart(2,'0')}`;const confidence=node.querySelector('.confidence');confidence.textContent=decision.review?'Review route':decision.hits.length?'Phrase match':'No clear match';confidence.classList.toggle('review',decision.review);node.querySelector('.reason').textContent=order.reason_for_exam;const select=node.querySelector('.route-select');select.innerHTML=state.catalog.map(item=>`<option ${item.protocol_name===order.predicted_protocol?'selected':''}>${escapeHtml(item.protocol_name)}</option>`).join('');select.addEventListener('change',e=>{order.predicted_protocol=e.target.value;});node.querySelector('.evidence').textContent=decision.review?'No single safe route was identified. Keep this request for radiologist review.':`Matched clinical phrases: ${decision.hits.join(', ')}.`;if(order.expected_protocol)node.querySelector('.reference').textContent=`Practice reference: ${order.expected_protocol}`;container.append(node);});}
function loadOrders(rows,name){if(!rows.every(row=>'study_description'in row&&'reason_for_exam'in row))throw new Error('CSV needs study_description and reason_for_exam columns.');state.orders=rows.map(row=>({...row}));$('file-name').textContent=name;render();}
async function loadBundled(){try{const [catalog,orders]=await Promise.all([fetch('../data/protocols.csv'),fetch('../data/orders.csv')]);if(!catalog.ok||!orders.ok)throw new Error();state.catalog=parseCsv(await catalog.text());loadOrders(parseCsv(await orders.text()),'Bundled examples');}catch{$('summary').textContent='Upload orders after loading the local catalog.';}}
$('orders-upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{loadOrders(parseCsv(await file.text()),file.name);}catch(error){alert(error.message);}e.target.value='';});
loadBundled();
