const state={studies:[],tracks:[],active:null};const $=id=>document.getElementById(id);
const TRACKS=[{id:'pulmonary',label:'Pulmonary nodules',hint:'Nodules and focal lung opacities',pattern:/\b(nodule|ground-glass opacity|subsolid|part-solid)\b/i},{id:'nodes',label:'Thoracic lymph nodes',hint:'Mediastinal and hilar nodes',pattern:/\b(lymph node|adenopathy|paratracheal|subcarinal|hilar|station 4r|ap window)\b/i},{id:'incidental',label:'Incidental findings',hint:'Thyroid or upper-abdominal findings',pattern:/\b(adrenal|thyroid)\b/i}];
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){field+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field='';}else field+=c;}if(quoted)throw new Error('CSV has an unmatched quotation mark.');if(field||row.length){row.push(field);rows.push(row);}const headers=rows.shift()?.map(h=>h.trim().replace(/^\uFEFF/,''));if(!headers||!rows.length)throw new Error('CSV needs a header and at least one row.');return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,(values[i]||'').trim()])));}
function sentenceFor(text,pattern){return text.split(/(?<=[.!?])\s+/).find(sentence=>pattern.test(sentence))||'';}
function statusFor(text,found){if(!found)return'not mentioned';const value=text.toLowerCase();if(/resolved|no longer identified|no recurrence/.test(value))return'resolved';if(/new\s|newly/.test(value))return'new';if(/increased|increase in size|enlarg|now measures|solid component/.test(value))return'increased';if(/decreased|smaller/.test(value))return'decreased';if(/stable|unchanged|similar/.test(value))return'stable';return'mentioned';}
function buildTracks(){state.tracks=TRACKS.map(track=>({...track,events:state.studies.map(study=>{const excerpt=sentenceFor(study.report_text,track.pattern);return{...study,excerpt,status:statusFor(excerpt,Boolean(excerpt))};})})).filter(track=>track.events.some(event=>event.excerpt));state.active=state.tracks[0]?.id||null;}
function renderList(){$('track-list').innerHTML=state.tracks.map(track=>`<button class="track-button ${track.id===state.active?'active':''}" data-id="${track.id}"><strong>${track.label}</strong><span>${track.hint}</span></button>`).join('');document.querySelectorAll('.track-button').forEach(button=>button.addEventListener('click',()=>{state.active=button.dataset.id;render();}));}
function renderDetail(){const track=state.tracks.find(item=>item.id===state.active);$('detail-content').hidden=!track;$('empty').hidden=Boolean(track);if(!track)return;$('track-title').textContent=track.label;$('track-count').textContent=`${track.events.length} studies in this history`;$('timeline').innerHTML=track.events.map((event,index)=>{const cls=['new','increased'].includes(event.status)?'alert':event.status==='not mentioned'?'unknown':'';return`<article class="event ${event.status.replace(' ','-')}"><div class="event-head"><time>${escapeHtml(event.study_date)}</time><span class="tag ${cls}">${event.status}</span></div><p>${escapeHtml(event.excerpt||'This finding was not mentioned in the report.')}</p></article>`;}).join('');const first=track.events.find(event=>event.excerpt)||track.events[0];$('source-date').textContent=first.study_date;$('source-text').textContent=first.report_text;document.querySelectorAll('.event').forEach((node,index)=>node.addEventListener('click',()=>{const event=track.events[index];$('source-date').textContent=event.study_date;$('source-text').textContent=event.report_text;}));}
function render(){renderList();renderDetail();}
function loadStudies(rows,name){if(!rows.every(row=>'study_date'in row&&'report_text'in row))throw new Error('CSV needs study_date and report_text columns.');state.studies=rows.sort((a,b)=>new Date(a.study_date)-new Date(b.study_date));buildTracks();$('history-name').textContent=`${name} · ${state.studies.length} studies`;render();}
async function loadBundled(){try{const response=await fetch('../data/patient-001.csv');if(!response.ok)throw new Error();loadStudies(parseCsv(await response.text()),'Bundled patient history');}catch{$('history-name').textContent='Upload a patient-history CSV to begin.';render();}}
$('history-upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{loadStudies(parseCsv(await file.text()),file.name);}catch(error){alert(error.message);}e.target.value='';});loadBundled();
